version: '3.8'
services:
  petlog_postgres:
    image: postgres:15
    shm_size: 1g
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      # to clear this run `docker volume rm simplelegal_data-volume`
      - data-volume:/var/lib/postgresql/data_petlog

volumes:
  data-volume:
