# Generated by Django 4.2.7 on 2023-11-30 07:51

from django.db import migrations
import scheduler_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='next_dose',
            field=scheduler_field.fields.SchedulerDateField(method_name='send_reminder_email'),
        ),
    ]
