# Generated by Django 4.2.7 on 2023-11-30 23:55

import datetime
from django.db import migrations
import scheduler_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='next_dose',
            field=scheduler_field.fields.SchedulerDateField(default=datetime.datetime(2023, 11, 30, 23, 55, 11, 82458), method_name='send_reminder_email'),
            preserve_default=False,
        ),
    ]
