# Generated by Django 4.2.7 on 2023-11-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_vaccine_next_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='remind_me',
            field=models.BooleanField(default=False),
        ),
    ]
