# Generated by Django 4.2.7 on 2023-11-25 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0002_remove_medicine_periodicty_entry_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="training",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="vaccine",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
