# Generated by Django 4.2.7 on 2023-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchedulerDateManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("function_name", models.CharField(max_length=50)),
                ("field_name", models.CharField(max_length=50)),
            ],
        ),
    ]
