# Generated by Django 4.2.7 on 2023-11-27 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler_field", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedulerdatemanager",
            old_name="function_name",
            new_name="method_name",
        ),
    ]
