# Generated by Django 4.2.7 on 2023-11-30 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
