# Generated by Django 4.2.7 on 2023-11-24 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_pet_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="updated_on",
        ),
    ]
