# Generated by Django 4.2.7 on 2023-11-24 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_remove_pet_created_on_remove_pet_updated_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="owner",
            new_name="guardian",
        ),
    ]
