# Generated by Django 4.2.7 on 2023-11-25 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_rename_owner_pet_guardian"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
