# Generated by Django 4.2.7 on 2023-11-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("species", models.CharField(max_length=30)),
                ("breed", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("created_on", models.DateTimeField()),
                ("updated_on", models.DateTimeField()),
            ],
        ),
    ]
